export const ALL_PERMISSIONS = {
    PATIENTS: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/patients', module: "PATIENTS" },
        CREATE: { method: "POST", apiPath: '/api/v1/add-patient', module: "PATIENTS" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/upadte-patient', module: "PATIENTS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/delete-patient/{id}', module: "PATIENTS" },
    },
    PERMISSIONS: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/permissions', module: "PERMISSIONS" },
        CREATE: { method: "POST", apiPath: '/api/v1/add-permission', module: "PERMISSIONS" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/update-permission', module: "PERMISSIONS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/delete-permission/{id}', module: "PERMISSIONS" },
    },
    ROLES: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/roles', module: "ROLES" },
        CREATE: { method: "POST", apiPath: '/api/v1/add-role', module: "ROLES" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/update-role', module: "ROLES" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/delete-role/{id}', module: "ROLES" },
    },
    USERS: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/users', module: "USERS" },
        CREATE: { method: "POST", apiPath: '/api/v1/add-user', module: "USERS" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/update-user', module: "USERS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/delete-user/{id}', module: "USERS" },
    },
    MEDICAL_EXAMS: {
        GET_PAGINATE_BY_PATIENT: { method: "GET", apiPath: '/api/v1/medical-exams/patient/{id}', module: "MEDICAL_EXAMS" },
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/medical-exams', module: "MEDICAL_EXAMS" },
        CREATE: { method: "POST", apiPath: '/api/v1/medical-exams', module: "MEDICAL_EXAMS" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/medical-exams', module: "MEDICAL_EXAMS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/medical-exams/{id}', module: "MEDICAL_EXAMS" },
    },
    CLINICAL_INFO: {
        GET_PAGINATE_BY_PATIENT: { method: "GET", apiPath: '/api/v1/clinical-info/patient/{id}', module: "CLINICAL_INFOS" },
        GET_PAGINATE_BY_ME: { method: "GET", apiPath: '/api/v1/clinical-info/medical-exam/{id}', module: "CLINICAL_INFOS" },
        CREATE: { method: "POST", apiPath: '/api/v1/clinical-info', module: "CLINICAL_INFOS" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/clinical-info', module: "CLINICAL_INFOS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/clinical-info/{id}', module: "CLINICAL_INFOS" },
    },
    VITAL_SIGNS: {
        GET_PAGINATE_BY_PATIENT: { method: "GET", apiPath: '/api/v1/vital-signs/patient/{id}', module: "VITAL_SIGNS" },
        GET_PAGINATE_BY_ME: { method: "GET", apiPath: '/api/v1/vital-signs/medical-exam/{id}', module: "VITAL_SIGNS" },
        CREATE: { method: "POST", apiPath: '/api/v1/vital-signs', module: "VITAL_SIGNS" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/vital-signs', module: "VITAL_SIGNS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/vital-signs/{id}', module: "VITAL_SIGNS" },
    },
    BLOOD_TEST: {
        GET_PAGINATE_BY_PATIENT: { method: "GET", apiPath: '/api/v1/blood-tests/patient/{id}', module: "BLOOD_TESTS" },
        GET_PAGINATE_BY_ME: { method: "GET", apiPath: '/api/v1/blood-tests/medical-exam/{id}', module: "BLOOD_TESTS" },
        CREATE: { method: "POST", apiPath: '/api/v1/blood-tests', module: "BLOOD_TESTS" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/blood-tests', module: "BLOOD_TESTS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/blood-tests/{id}', module: "BLOOD_TESTS" },
    },
    RADIOLOGY: {
        GET_PAGINATE_BY_PATIENT: { method: "GET", apiPath: '/api/v1/radiology/patient/{id}', module: "RADIOLOGIES" },
        GET_PAGINATE_BY_ME: { method: "GET", apiPath: '/api/v1/radiology/medical-exam/{id}', module: "RADIOLOGIES" },
        CREATE: { method: "POST", apiPath: '/api/v1/radiology', module: "RADIOLOGIES" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/radiology', module: "RADIOLOGIES" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/radiology/{id}', module: "RADIOLOGIES" },
    },
    DIAGNOSE: {
        GET_PAGINATE_BY_PATIENT: { method: "GET", apiPath: '/api/v1/diagnose-final/patient/{id}', module: "DIAGNOSE_FINALS" },
        GET_PAGINATE_BY_ME: { method: "GET", apiPath: '/api/v1/diagnose-final/medical-exam/{id}', module: "DIAGNOSE_FINALS" },
        CREATE: { method: "POST", apiPath: '/api/v1/diagnose-final', module: "DIAGNOSE_FINALS" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/diagnose-final', module: "DIAGNOSE_FINALS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/diagnose-final/{id}', module: "DIAGNOSE_FINALS" },
    },
    APPOINTMENTS: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/appointments', module: "APPOINTMENTS" },
        CREATE: { method: "POST", apiPath: '/api/v1/appointments', module: "APPOINTMENTS" },
        UPDATE: { method: "PUT", apiPath: '/api/v1/appointments', module: "APPOINTMENTS" },
        DELETE: { method: "DELETE", apiPath: '/api/v1/appointments/{id}', module: "APPOINTMENTS" },
    },
    DEPARTMENTS: {
        GET_PAGINATE: { method: "GET", apiPath: '/api/v1/departments', module: "DEPARTMENTS" },
    },
}